"""Manual deny-marker scan for the AI sidejob roadmap draft."""
import sys
import re
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")
content = Path("data/articles/_drafts/ai_sidejob_30day_roadmap_20260512.md").read_text(encoding="utf-8")

markers = [
    "〇〇", "◯◯", "○○", "△△", "××", "□□", "■■",
    "Bluesky", "Threads", "Mastodon", "トレンド入り",
    "架空", "Dr. X", "仮名", "仮称", "フィクション",
    "AIが生成", "AIによって生成", "AIで自動生成", "Generated by",
]
hits = [m for m in markers if m in content]
print(f"deny-marker hits: {hits if hits else 'none OK'}")

fp = [
    r"月\d+万円達成",
    r"誰でも稼げる",
    r"誰でも\d+万円",
    r"100%稼げる",
    r"絶対に稼げる",
    r"確実に\d+万円",
]
for p in fp:
    m = re.search(p, content)
    if m:
        print(f"forbidden phrase hit: {p} -> {m.group()}")
print("scan done")
