"""Strip the AI-disclosure ⚠️免責事項 footer from already-published note articles.

Background: 2026-05-08 audit revealed 26 published note articles still
carry "本記事の店舗・施設情報は…AIが構成しています" — the old text from
``main.py:_AI_DISCLAIMER_BLOCK`` (now reworded + gated to STORE_BLOCK
articles only).

This script identifies affected articles, removes the disclaimer block,
and updates them via ``NotePublisher.edit_article``.

Defaults to **dry-run**. Pass ``--apply`` to actually perform edits.
"""
from __future__ import annotations

import argparse
import glob
import json
import logging
import os
import re
import sys
from pathlib import Path

if sys.platform == "win32" and hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

_REPO = Path(__file__).resolve().parent.parent
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

env_file = _REPO / ".env"
if env_file.exists():
    for line in env_file.read_text(encoding="utf-8").splitlines():
        if "=" in line and not line.startswith("#"):
            k, v = line.split("=", 1)
            os.environ.setdefault(k.strip(), v.strip())

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("strip_ai_disclaimer")


# Pattern that matches the legacy disclaimer block (heading + body + sentinel).
# Three variants exist due to past sentinel renames:
#   1. Original: <!-- AI_DISCLAIMER --> + ## ⚠️ 免責事項
#   2. Heading-only (LLM-authored): ## ⚠️ 免責事項 / ## 免責事項
#   3. New gated form: <!-- STORE_DATA_DISCLAIMER --> + ## ご利用にあたって
# We only strip variant 1 + 2 (legacy AI-disclosure form). Variant 3 is
# the new sanctioned form for store articles and stays.
_LEGACY_DISCLAIMER_RE = re.compile(
    r"\n*---\s*\n+(?:<!--\s*AI_DISCLAIMER\s*-->\s*\n)?"
    r"##\s*[^\n]{0,6}免責事項[^\n]*\n+"
    r"[^\n]*(?:AI|ChatGPT|Claude|Gemini|GPT)[^\n]*(?:生成|作成|構成|執筆)[^\n]*\n*",
    re.MULTILINE,
)


def _strip_disclaimer(content: str) -> tuple[str, bool]:
    """Return ``(cleaned, changed)``. Idempotent."""
    cleaned, n = _LEGACY_DISCLAIMER_RE.subn("\n", content)
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
    return cleaned, n > 0


def _candidates() -> list[tuple[Path, str, str, str]]:
    """Return [(path, url, title, content), ...] for affected articles."""
    out: list[tuple[Path, str, str, str]] = []
    for path_str in glob.glob(str(_REPO / "data" / "articles" / "*.json")):
        path = Path(path_str)
        try:
            d = json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            continue
        url = d.get("published_url") or d.get("url")
        if not url or "note.com" not in url:
            continue
        content = d.get("content") or ""
        if not content:
            continue
        # Crude pre-check before regex — fast path.
        if not (
            "AIが構成" in content
            or "AIが生成" in content
            or "AIによって生成" in content
            or "本記事はAI" in content
            or "Generated by Claude" in content
            or "Generated by ChatGPT" in content
        ):
            continue
        out.append((path, url, d.get("title", "")[:80], content))
    return out


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--apply", action="store_true",
        help="Actually edit articles. Default is dry-run.",
    )
    parser.add_argument(
        "--limit", type=int, default=0,
        help="Process at most N articles (0 = all).",
    )
    args = parser.parse_args()

    cands = _candidates()
    logger.info("Found %d candidates with legacy AI disclaimer", len(cands))
    if args.limit:
        cands = cands[: args.limit]

    if not args.apply:
        logger.warning("DRY-RUN — pass --apply to perform edits")

    if args.apply:
        # Lazy import — only needed when actually editing.
        from publishers.note_publisher import NotePublisher
        publisher = NotePublisher()
    else:
        publisher = None

    edited = 0
    skipped = 0
    failed = 0
    for path, url, title, content in cands:
        cleaned, changed = _strip_disclaimer(content)
        if not changed:
            logger.info("[skip] %s — no legacy block matched", title[:50])
            skipped += 1
            continue
        delta = len(content) - len(cleaned)
        logger.info(
            "[%s] %s — strip %d chars   url=%s",
            "EDIT" if args.apply else "DRY ", title[:50], delta, url,
        )
        if not args.apply:
            continue
        try:
            ok = publisher.edit_article(
                url=url,
                new_title=None,  # title unchanged
                new_content=cleaned,
            )
            if ok:
                edited += 1
                # Update local JSON to keep auditing aligned.
                d = json.loads(path.read_text(encoding="utf-8"))
                d["content"] = cleaned
                d["legacy_ai_disclaimer_stripped_at"] = (
                    "2026-05-08"
                )
                path.write_text(
                    json.dumps(d, ensure_ascii=False, indent=2),
                    encoding="utf-8",
                )
            else:
                failed += 1
        except Exception as exc:
            logger.error("edit failed: %s — %s", title[:50], exc)
            failed += 1

    if publisher is not None:
        try:
            publisher.close()
        except Exception:
            pass

    logger.info(
        "DONE — edited=%d skipped=%d failed=%d", edited, skipped, failed,
    )
    return 0 if failed == 0 else 4


if __name__ == "__main__":
    raise SystemExit(main())
