"""Regression test suite for hallucination deny patterns.

Validates that:
1. Every regex in `config/settings.yaml` `evidence.forbidden_phrases`
   compiles successfully.
2. Every regex in `main.py:_PUBLISH_DENY_PATTERNS` compiles.
3. Each known hallucination case (positive sample) is BLOCKED.
4. Each known false-positive risk (negative sample) is NOT blocked.
5. `content_sanitizer.sanitize()` strips AI disclosure footers and
   placeholder phrases without garbling adjacent paragraphs.

Run as: ``py scripts/test_hallucination_deny.py``

Exits with non-zero status if any case fails. Intended to be wired
into CI / pre-commit.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

if sys.platform == "win32" and hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

_REPO = Path(__file__).resolve().parent.parent
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

import yaml  # noqa: E402

from generators.content_sanitizer import sanitize  # noqa: E402
from generators.objective_scorer import ObjectiveScorer  # noqa: E402


# Each tuple: (label, sample_text, should_be_blocked).
# Positive samples MUST be blocked. Negative samples MUST NOT.
DENY_TEST_CASES: list[tuple[str, str, bool]] = [
    # ── 伏字 + 業態語 (2026-05-07 一人飯記事の元凶) ──
    ("伏字-寿司",          "## おすすめ\n## ○○寿司\n素晴らしい店\n",         True),
    ("伏字-焼鳥",          "## ××焼鳥は最高\n素晴らしい店\n",                 True),
    ("伏字-ラーメン",      "## □□ラーメンの実力\nスープ最高\n",                 True),
    ("伏字-バル",          "## △△バルでデート\n雰囲気抜群\n",                 True),
    ("伏字-カフェ",        "○○カフェは隠れ家。\n",                              True),
    ("伏字-居酒屋",        "××居酒屋でしっぽり一杯。\n",                         True),
    ("伏字-イタリアン",    "□□イタリアンは絶品。\n",                             True),
    ("伏字-鮨",            "○○鮨の大トロ。\n",                                  True),
    ("伏字+店字",          "○○本店に行ってみた。\n",                             True),
    ("伏字-太字",          "**○○○○ ** が話題。\n",                              True),
    ("伏字-鉤括弧",        "「○○○」が流行している。\n",                          True),

    # ── 仮名/仮称/架空 markers (2026-05-08 東京特定エリア記事) ──
    ("仮名フィクション",   "「□□」（仮名）の店。\n",                              True),
    ("仮称マーカー",       "ある居酒屋（仮称）に伺った。\n",                       True),
    ("ダッシュ伏字",       "ーー寿司に行った。\n",                                True),

    # ── A/B/C 記号命名 (2026-04-23 ダルゴナ事故) ──
    ("A/B/C-専門店",       "## ダルゴナ専門店A\nおすすめ\n",                       True),
    ("A/B/C-ブランド",     "韓国コスメブランドBが流行\n",                          True),

    # ── プロンプト残留 placeholder ──
    ("ここに入力",         "参考リンク: ここに入力\n",                            True),
    ("URLは記載しません",  "詳細URL: URLは記載しません\n",                       True),
    ("実際にはURL",        "実際にはこのURLを参照\n",                              True),

    # ── 架空アンケート/調査主張 (2026-06-10 【100人に聞いた】scrap 事故) ──
    ("N人に聞いた",        "【100人に聞いた】DB移行で失敗しない方法\n",            True),
    ("N人にアンケート",    "エンジニア50人にアンケートを実施\n",                   True),

    # ── Bluesky/Threads/Mastodon 架空投稿 ──
    ("Bluesky氏の投稿",    "習近平氏のBluesky投稿が話題\n",                       True),
    ("Threads徹底",        "妻夫木聡さんのThreads投稿を徹底\n",                   True),
    ("Mastodon読み解",     "李在明氏のMastodon投稿から読み解\n",                  True),

    # ── 架空ニュースイベント ──
    ("トレンド入り",       "ハッシュタグ #X がトレンド入り\n",                    True),
    ("大きな話題",         "Vogue Korea がメディアで大きな話題を呼んでいます\n",  True),
    ("賛否両論",           "賛否両論が大きく交錯\n",                              True),

    # ── 内部 knowledge-topic URI / 媒体名 placeholder (2026-07-13 事故#22) ──
    ("内部URI-underscore", "根拠です（出典: knowledge_topic://kc_006）。\n",      True),
    ("内部URI-hyphen",     "> 出典: 媒体名 — knowledge-topic://hg_007\n",         True),
    ("媒体名placeholder",  "> 出典: 媒体名 — https://example.com\n",              True),

    # ── 裏付け不能な科学的証明の断定 (2026-07-14 事故#24) ──
    ("科学が証明した",     "科学が証明した「体温を下げる3ステップ戦略」\n",        True),
    ("科学的に証明された", "この効果は科学的に証明されたものです。\n",             True),
    ("正常-証明書",        "SSL証明書を更新した。\n",                             False),
    ("正常-科学的な説明",  "科学的な視点から説明を試みる。\n",                     False),

    # ── AI 開示 footer (2026-05-08 拡充) ──
    ("AI生成-本記事は",    "本文。\n\n本記事はAIで自動生成しました。\n",          True),
    ("AI生成-構成",        "本文。\n\n本記事の店舗情報はAIが構成しています。\n",  True),
    ("AI生成-別形",        "AIによって生成されたものです。\n",                    True),
    ("AI生成-による",      "ChatGPTによる自動生成です。\n",                       True),
    ("AI生成-注釈型",      "※ AI 生成記事です\n",                                True),
    ("AI生成-英語",        "Generated by Claude\n",                              True),
    ("AI生成-免責",        "免責事項: 本記事の正確性は保証いたしません。\n",      True),

    # ── 既存パターン: チェーン店は scorer 別経路で処理 ──

    # ── ネガティブケース: 誤爆してはならない ──
    ("正常-実在店",        "## 焼鳥 鳥さわ @亀戸\n鳥しき出身の名店\n",            False),
    ("正常-実在ラーメン",  "## 麺屋 翔 本店\n百名店8年連続\n",                    False),
    ("正常-Claude技術",    "Claudeを使ったテクニックを紹介する記事です。\n",      False),
    ("正常-AI技術解説",    "AIエージェントの仕組みを解説する。\n",                False),
    ("正常-空白伏字",      "○○ 寿司 (with space)\n",                            False),
    ("正常-スタイル A",    "コーディングスタイル A を採用した。\n",                False),
    ("正常-モデル B",      "比較対象として、モデル B を試した。\n",                False),
    ("正常-Aクラス",       "Aクラスのレストランで食事した。\n",                    False),
]


# Sanitizer-specific cases: (label, input, expected_marker_in_log)
# expected_marker None means "should NOT be sanitized".
SANITIZER_CASES: list[tuple[str, str, str | None]] = [
    ("AI開示-本記事は",
     "タイトル\n\n本記事はAIで自動生成しました。\n\n通常本文",
     "ai_disclosure"),
    ("AI開示-構成",
     "タイトル\n\n本記事の店舗情報はAIが構成しています。\n",
     "ai_disclosure"),
    ("AI開示-免責",
     "本文\n\n免責事項: 本記事の正確性は保証いたしません。\n",
     "ai_disclosure"),
    ("AI開示-Generated",
     "Body.\n\nGenerated by Claude.\n",
     "ai_disclosure"),
    ("正常-Claude文脈",
     "タイトル\n\nClaudeを使うと便利です。\n",
     None),
    ("既存-ここに入力",
     "本文\n\n参考リンク: ここに入力\n",
     "line_kill"),
    ("既存-架空のURL",
     "本文\n\n架空のURL を残してしまった\n",
     "line_kill"),
    # ── 2026-07-13 事故#22: 内部URI出典の3形態 ──
    ("内部URI-inline",
     "ハードルを下げているんです（出典: knowledge_topic://kc_006）。続き。\n",
     "internal_uri_inline"),
    ("内部URI-blockquote",
     "> 「引用文です。」\n> 出典: 媒体名 — knowledge-topic://hg_007\n\n次の段落。\n",
     "internal_uri_blockquote"),
    ("内部URI-bare",
     "（比較データは knowledge_topic://cmp_001 参照）という表記。\n",
     "internal_uri_bare"),
    # Codex review 2026-07-13: Source: 形と、URI 直後に日本語が続く形
    # (旧 \\S* 貪欲マッチだと「）。続き」まで食っていた)
    ("内部URI-Source形",
     "> \"quote text\"\n> Source: knowledge-topic://xy_001\n\n次の段落。\n",
     "internal_uri_blockquote"),
    ("内部URI-日本語後続",
     "詳細は knowledge_topic://kc_006）。続きの文章は残るべき。\n",
     "internal_uri_bare"),
    ("正常-実URL出典",
     "> 「引用文です。」\n> 出典: ROOMIE — https://www.roomie.jp/2026/07/1825126/\n",
     None),
    # ── 2026-07-14 事故レビュー: 体裁バグの自動修復 ──
    ("二重ハッシュ見出し",
     "本文。\n\n## ## 参考文献\n\n- リンク\n",
     "double_hash_heading"),
    ("取得日の年ずれ",
     "> 出典: ROOMIE — https://roomie.jp/x (取得日: 2024年6月20日)\n",
     "retrieval_date_normalized"),
    # ── 2026-07-15 backlog#16: LLM 偽アンカーリンク+架空オファー ──
    ("偽アンカーリンク",
     "本文。\n\n- [オルビス公式 — トライアルセット](# オルビス) - 初回購入¥1,000\n\n続き。\n",
     "fake_anchor_link"),
    ("正常-実URLリンク",
     "- [ROOMIE](https://www.roomie.jp/abc) - 元記事\n",
     None),
]

# 完結性ガード (2026-07-13 事故#23): (label, input, should_be_incomplete)
COMPLETENESS_CASES: list[tuple[str, str, bool]] = [
    ("切断-読点終端",
     "## アクセス\n\n益善洞エリアは、**鍾路3街駅の4番出口周辺**から徒歩圏内に、", True),
    ("切断-太字未閉",
     "本文です。\n\n**【パターンB：継続的・網", True),
    ("切断-空見出し",
     "本文があります。\n\n### 💡 【図解】用途別 カメラ選定", True),
    # Codex review 2026-07-13 追加: 構造行の中の切断と未閉フェンス
    ("切断-リスト項目読点",
     "理由の一覧:\n\n- 一つ目の理由です。\n- 二つ目の理由は、", True),
    # 2026-07-15 backlog#13a: 長文リスト項目の mid-word 切断 (ブロワー実害)
    ("切断-長文リスト項目",
     "基準:\n\n1. **安全設計が最優先であること:** 単なる稼働時間だけでなく、過度な温度上昇を防ぐ機能や充電切れを未然に防", True),
    ("正常-長文リスト項目完結",
     "基準:\n\n1. **安全設計:** 過度な温度上昇を防ぐ自動停止機能を最初に確認しましょう。", False),
    ("切断-未閉コードフェンス",
     "図解です。\n\n```mermaid\ngraph TD\n    A --> B", True),
    ("正常-句点終端",
     "公式サイトで最新情報を確認しましょう。", False),
    ("正常-テーブル終端",
     "## まとめ\n\n本文。\n\n| A | B |\n| - | - |\n| 1 | 2 |", False),
    ("正常-リスト終端",
     "揃えたいアイテム:\n\n- 予備バッテリー\n- NDフィルター", False),
    ("正常-コードフェンス終端",
     "図解です。\n\n```mermaid\ngraph TD\n    A --> B\n```", False),
]


def main() -> int:
    failures: list[str] = []

    # 1. Validate settings.yaml regex compilation.
    settings_path = _REPO / "config" / "settings.yaml"
    with settings_path.open(encoding="utf-8") as f:
        cfg = yaml.safe_load(f)
    forbidden = cfg["evidence"]["forbidden_phrases"]
    print(f"[1] Validating {len(forbidden)} forbidden_phrases regex...")
    for raw in forbidden:
        try:
            re.compile(raw)
        except re.error as exc:
            failures.append(f"settings.yaml regex invalid: {raw!r} ({exc})")
    if not failures:
        print("    OK - all regex compile")

    # 2. Validate settings.yaml.example regex too.
    example_path = _REPO / "config" / "settings.yaml.example"
    with example_path.open(encoding="utf-8") as f:
        example_cfg = yaml.safe_load(f)
    example_forbidden = example_cfg["evidence"]["forbidden_phrases"]
    print(f"[2] Validating {len(example_forbidden)} example regex...")
    for raw in example_forbidden:
        try:
            re.compile(raw)
        except re.error as exc:
            failures.append(
                f"settings.yaml.example regex invalid: {raw!r} ({exc})"
            )
    if not failures or len(failures) <= 1:
        print("    OK - all example regex compile")

    # 3. Validate main.py _PUBLISH_DENY_PATTERNS by importing it.
    print("[3] Importing main module to verify _PUBLISH_DENY_PATTERNS...")
    try:
        import main  # noqa: F401
        print("    OK - main imports cleanly")
    except Exception as exc:
        failures.append(f"main.py import failed: {exc}")

    # 4. Test deny cases against ObjectiveScorer.
    scorer = ObjectiveScorer()
    print(f"[4] Running {len(DENY_TEST_CASES)} deny test cases...")
    for label, text, should_block in DENY_TEST_CASES:
        result = scorer._score_forbidden_phrases(text, forbidden)
        blocked = result["grade"] == "Fail"
        if blocked != should_block:
            failures.append(
                f"DENY MISMATCH [{label}]: blocked={blocked} "
                f"expected={should_block} text={text[:60]!r} hits={result['hits'][:2]}"
            )
        else:
            mark = "BLOCK" if blocked else "PASS "
            print(f"    [{mark}] {label}")

    # 5. Test sanitizer cases.
    print(f"[5] Running {len(SANITIZER_CASES)} sanitizer cases...")
    for label, text, expected in SANITIZER_CASES:
        cleaned, removed = sanitize(text)
        if expected is None:
            if removed:
                failures.append(
                    f"SANITIZER FALSE-POSITIVE [{label}]: "
                    f"removed={removed} text={text[:60]!r}"
                )
            else:
                print(f"    [PASS]  {label}")
        else:
            has_match = any(expected in r for r in removed)
            if not has_match:
                failures.append(
                    f"SANITIZER MISS [{label}]: expected={expected!r} "
                    f"got removed={removed} text={text[:60]!r}"
                )
            # Codex review 2026-07-13: removal-log だけでなく cleaned
            # output 側にも残骸 (内部URI / 媒体名 / 空の出典行) が
            # 残っていないことを assert する。
            elif expected.startswith("internal_uri"):
                residue = re.search(
                    r"knowledge[-_]topic://|媒体名"
                    r"|^>\s*(?:出典[:：]|Source:)\s*$",
                    cleaned, re.MULTILINE | re.IGNORECASE,
                )
                if residue:
                    failures.append(
                        f"SANITIZER RESIDUE [{label}]: "
                        f"cleaned still contains {residue.group(0)!r}"
                    )
                else:
                    print(f"    [STRIP] {label} (residue-free)")
            else:
                print(f"    [STRIP] {label}")

    # 6. RAG hallucination retriever — Sprint 2 (2026-05-11).
    # Verify the semantic guard correctly flags planted patterns and
    # leaves clean topical articles alone. Skipped gracefully when the
    # index hasn't been built (CI without ML deps).
    print("[6] Validating RAG hallucination retriever ...")
    # Samples are intentionally realistic-length (200-500 chars).
    # The retriever uses 1500-char body + 1000-char mid in its query
    # builder; very short samples (<100 chars) get poor embedding
    # representation and miss matches that production-length articles
    # catch fine.
    rag_cases: list[tuple[str, str, int]] = [
        # (label, sample, min_expected_hits)
        ("rag-伏字寿司",
         "今回紹介する3軒は〇〇寿司、××焼鳥、□□ラーメン。"
         "それぞれカウンター席が快適で、地元客に愛されている店ばかり。"
         "予約は電話のみ、現金決済推奨。\n",
         1),
        ("rag-AI開示",
         "店舗A、店舗Bと比較しても、味は群を抜いていました。\n"
         "## ご利用にあたって\n"
         "本記事はAIで生成しました。"
         "免責事項：本記事の内容の正確性は保証しません。",
         1),
        ("rag-clean-tech",
         "Claude Code は Anthropic の CLI ツールで、ターミナルから "
         "AI コーディング支援が受けられる。GitHub の公式リポジトリで "
         "OSS として公開されており、Mac/Linux/Windows いずれでも動作する。"
         "サブスクリプションは Anthropic Console から管理。",
         0),
        # 2026-06-15 (Codex #4): broaden the negative corpus beyond a single
        # clean-tech sample so the multi-query expansion's wider candidate
        # pool can't silently start false-positiving on the system's real
        # genres. Each is a production-length, fully-grounded article that
        # must NOT trip the guard (no 伏字 / no AI 開示 / no fabricated SNS).
        ("rag-clean-gadget",
         "サムスンの次期フラッグシップ Galaxy S27 Pro は 6.5 型ディスプレイに "
         "5000mAh バッテリーを搭載すると複数のリーク情報が報じている。"
         "前モデル比で駆動時間の改善が見込まれ、急速充電にも対応する見通し。"
         "正式発表は来年初頭とされ、価格帯は据え置きと予想されている。"
         "実機レビューは発表後に追記する。",
         0),
        ("rag-clean-kbeauty",
         "ナイアシンアミドは皮膚科学の査読論文でメラニン生成抑制が報告されている "
         "ビタミンB3 誘導体で、一般的な化粧水では 2〜5% 配合が多い。"
         "セラミドはバリア機能の補修に寄与する角層成分で、保湿の基礎となる。"
         "いずれも刺激は比較的穏やかだが、初使用時はパッチテストを推奨する。"
         "出典は各成分の一次文献に基づく。",
         0),
        ("rag-clean-shop",
         "東京・神保町の老舗喫茶『さぼうる』は 1955 年創業で、深煎りの "
         "ブレンドコーヒーと名物のナポリタンで知られる。"
         "店内は木目調の落ち着いた内装で、昼時は近隣の会社員で賑わう。"
         "現金決済のみ、予約は不可。最寄りは神保町駅 A7 出口から徒歩 1 分。"
         "営業時間は公式情報を確認のこと。",
         0),
        ("rag-clean-news",
         "経済産業省は半導体補助金の新たな枠組みを公表した。"
         "国内製造拠点の新設・増設を対象に、設備投資額の一部を補助する。"
         "対象企業の選定基準と申請期間は公式サイトで告知される予定。"
         "業界団体は供給網の強靭化につながると一定の評価を示した。"
         "詳細は省庁の一次発表を参照のこと。",
         0),
        ("rag-clean-travel",
         "韓国・ソウルの聖水洞はかつての工場地帯がリノベーションされ、"
         "個人経営のロースタリーカフェやセレクトショップが集まるエリアになった。"
         "週末は若者で賑わい、ギャラリーを併設した店舗も多い。"
         "地下鉄 2 号線の聖水駅が最寄りで、徒歩圏に見どころが集中している。"
         "営業時間は店舗ごとに異なるため事前確認を推奨する。",
         0),
    ]
    rag_results: list[tuple[str, int, bool]] = []
    try:
        from main import _retrieve_hallucination_warnings  # noqa: E402
        for label, sample, min_hits in rag_cases:
            hits = _retrieve_hallucination_warnings(sample)
            ok = len(hits) >= min_hits if min_hits > 0 else len(hits) == 0
            rag_results.append((label, len(hits), ok))
            tag = "OK" if ok else "FAIL"
            print(f"    [{tag}] {label}: {len(hits)} hits (need {'>=' if min_hits>0 else '=='}{min_hits})")
        rag_failures = [r for r in rag_results if not r[2]]
        if rag_failures:
            for label, hits, _ in rag_failures:
                failures.append(
                    f"RAG GUARD [{label}]: got {hits} hits (expectation mismatch)"
                )
    except ImportError as exc:
        print(f"    SKIP - RAG deps not available: {exc}")
    except Exception as exc:
        print(f"    SKIP - RAG retriever unavailable: {exc}")

    # 7. Completeness guard (2026-07-13 incident #23): truncated tails
    # must be detected; complete structural endings must not be.
    print(f"[7] Running {len(COMPLETENESS_CASES)} completeness cases...")
    from generators.content_sanitizer import is_incomplete, trim_incomplete_tail
    for label, text, should_flag in COMPLETENESS_CASES:
        reason = is_incomplete(text)
        trimmed, removed = trim_incomplete_tail(text)
        if should_flag:
            if not reason:
                failures.append(
                    f"COMPLETENESS MISS [{label}]: is_incomplete=None "
                    f"text tail={text[-60:]!r}"
                )
            elif not removed:
                failures.append(
                    f"COMPLETENESS TRIM MISS [{label}]: nothing trimmed"
                )
            else:
                print(f"    [FLAG]  {label}: {reason[:50]}")
        else:
            if reason or removed:
                failures.append(
                    f"COMPLETENESS FALSE-POSITIVE [{label}]: "
                    f"reason={reason!r} removed={removed}"
                )
            else:
                print(f"    [PASS]  {label}")

    # 8. Summary.
    print()
    if failures:
        print(f"FAIL: {len(failures)} test(s) failed:")
        for f in failures:
            print(f"  - {f}")
        return 1
    print(
        f"PASS: all {len(DENY_TEST_CASES)} deny + "
        f"{len(SANITIZER_CASES)} sanitizer + "
        f"{len(COMPLETENESS_CASES)} completeness + "
        f"{len(rag_results)} RAG cases OK"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
