"""Regression test suite for hallucination deny patterns.

Validates that:
1. Every regex in `config/settings.yaml` `evidence.forbidden_phrases`
   compiles successfully.
2. Every regex in `main.py:_PUBLISH_DENY_PATTERNS` compiles.
3. Each known hallucination case (positive sample) is BLOCKED.
4. Each known false-positive risk (negative sample) is NOT blocked.
5. `content_sanitizer.sanitize()` strips AI disclosure footers and
   placeholder phrases without garbling adjacent paragraphs.

Run as: ``py scripts/test_hallucination_deny.py``

Exits with non-zero status if any case fails. Intended to be wired
into CI / pre-commit.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

if sys.platform == "win32" and hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

_REPO = Path(__file__).resolve().parent.parent
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

import yaml  # noqa: E402

from generators.content_sanitizer import sanitize  # noqa: E402
from generators.objective_scorer import ObjectiveScorer  # noqa: E402


# Each tuple: (label, sample_text, should_be_blocked).
# Positive samples MUST be blocked. Negative samples MUST NOT.
DENY_TEST_CASES: list[tuple[str, str, bool]] = [
    # ── 伏字 + 業態語 (2026-05-07 一人飯記事の元凶) ──
    ("伏字-寿司",          "## おすすめ\n## ○○寿司\n素晴らしい店\n",         True),
    ("伏字-焼鳥",          "## ××焼鳥は最高\n素晴らしい店\n",                 True),
    ("伏字-ラーメン",      "## □□ラーメンの実力\nスープ最高\n",                 True),
    ("伏字-バル",          "## △△バルでデート\n雰囲気抜群\n",                 True),
    ("伏字-カフェ",        "○○カフェは隠れ家。\n",                              True),
    ("伏字-居酒屋",        "××居酒屋でしっぽり一杯。\n",                         True),
    ("伏字-イタリアン",    "□□イタリアンは絶品。\n",                             True),
    ("伏字-鮨",            "○○鮨の大トロ。\n",                                  True),
    ("伏字+店字",          "○○本店に行ってみた。\n",                             True),
    ("伏字-太字",          "**○○○○ ** が話題。\n",                              True),
    ("伏字-鉤括弧",        "「○○○」が流行している。\n",                          True),

    # ── 仮名/仮称/架空 markers (2026-05-08 東京特定エリア記事) ──
    ("仮名フィクション",   "「□□」（仮名）の店。\n",                              True),
    ("仮称マーカー",       "ある居酒屋（仮称）に伺った。\n",                       True),
    ("ダッシュ伏字",       "ーー寿司に行った。\n",                                True),

    # ── A/B/C 記号命名 (2026-04-23 ダルゴナ事故) ──
    ("A/B/C-専門店",       "## ダルゴナ専門店A\nおすすめ\n",                       True),
    ("A/B/C-ブランド",     "韓国コスメブランドBが流行\n",                          True),

    # ── プロンプト残留 placeholder ──
    ("ここに入力",         "参考リンク: ここに入力\n",                            True),
    ("URLは記載しません",  "詳細URL: URLは記載しません\n",                       True),
    ("実際にはURL",        "実際にはこのURLを参照\n",                              True),

    # ── Bluesky/Threads/Mastodon 架空投稿 ──
    ("Bluesky氏の投稿",    "習近平氏のBluesky投稿が話題\n",                       True),
    ("Threads徹底",        "妻夫木聡さんのThreads投稿を徹底\n",                   True),
    ("Mastodon読み解",     "李在明氏のMastodon投稿から読み解\n",                  True),

    # ── 架空ニュースイベント ──
    ("トレンド入り",       "ハッシュタグ #X がトレンド入り\n",                    True),
    ("大きな話題",         "Vogue Korea がメディアで大きな話題を呼んでいます\n",  True),
    ("賛否両論",           "賛否両論が大きく交錯\n",                              True),

    # ── AI 開示 footer (2026-05-08 拡充) ──
    ("AI生成-本記事は",    "本文。\n\n本記事はAIで自動生成しました。\n",          True),
    ("AI生成-構成",        "本文。\n\n本記事の店舗情報はAIが構成しています。\n",  True),
    ("AI生成-別形",        "AIによって生成されたものです。\n",                    True),
    ("AI生成-による",      "ChatGPTによる自動生成です。\n",                       True),
    ("AI生成-注釈型",      "※ AI 生成記事です\n",                                True),
    ("AI生成-英語",        "Generated by Claude\n",                              True),
    ("AI生成-免責",        "免責事項: 本記事の正確性は保証いたしません。\n",      True),

    # ── 既存パターン: チェーン店は scorer 別経路で処理 ──

    # ── ネガティブケース: 誤爆してはならない ──
    ("正常-実在店",        "## 焼鳥 鳥さわ @亀戸\n鳥しき出身の名店\n",            False),
    ("正常-実在ラーメン",  "## 麺屋 翔 本店\n百名店8年連続\n",                    False),
    ("正常-Claude技術",    "Claudeを使ったテクニックを紹介する記事です。\n",      False),
    ("正常-AI技術解説",    "AIエージェントの仕組みを解説する。\n",                False),
    ("正常-空白伏字",      "○○ 寿司 (with space)\n",                            False),
    ("正常-スタイル A",    "コーディングスタイル A を採用した。\n",                False),
    ("正常-モデル B",      "比較対象として、モデル B を試した。\n",                False),
    ("正常-Aクラス",       "Aクラスのレストランで食事した。\n",                    False),
]


# Sanitizer-specific cases: (label, input, expected_marker_in_log)
# expected_marker None means "should NOT be sanitized".
SANITIZER_CASES: list[tuple[str, str, str | None]] = [
    ("AI開示-本記事は",
     "タイトル\n\n本記事はAIで自動生成しました。\n\n通常本文",
     "ai_disclosure"),
    ("AI開示-構成",
     "タイトル\n\n本記事の店舗情報はAIが構成しています。\n",
     "ai_disclosure"),
    ("AI開示-免責",
     "本文\n\n免責事項: 本記事の正確性は保証いたしません。\n",
     "ai_disclosure"),
    ("AI開示-Generated",
     "Body.\n\nGenerated by Claude.\n",
     "ai_disclosure"),
    ("正常-Claude文脈",
     "タイトル\n\nClaudeを使うと便利です。\n",
     None),
    ("既存-ここに入力",
     "本文\n\n参考リンク: ここに入力\n",
     "line_kill"),
    ("既存-架空のURL",
     "本文\n\n架空のURL を残してしまった\n",
     "line_kill"),
]


def main() -> int:
    failures: list[str] = []

    # 1. Validate settings.yaml regex compilation.
    settings_path = _REPO / "config" / "settings.yaml"
    with settings_path.open(encoding="utf-8") as f:
        cfg = yaml.safe_load(f)
    forbidden = cfg["evidence"]["forbidden_phrases"]
    print(f"[1] Validating {len(forbidden)} forbidden_phrases regex...")
    for raw in forbidden:
        try:
            re.compile(raw)
        except re.error as exc:
            failures.append(f"settings.yaml regex invalid: {raw!r} ({exc})")
    if not failures:
        print("    OK - all regex compile")

    # 2. Validate settings.yaml.example regex too.
    example_path = _REPO / "config" / "settings.yaml.example"
    with example_path.open(encoding="utf-8") as f:
        example_cfg = yaml.safe_load(f)
    example_forbidden = example_cfg["evidence"]["forbidden_phrases"]
    print(f"[2] Validating {len(example_forbidden)} example regex...")
    for raw in example_forbidden:
        try:
            re.compile(raw)
        except re.error as exc:
            failures.append(
                f"settings.yaml.example regex invalid: {raw!r} ({exc})"
            )
    if not failures or len(failures) <= 1:
        print("    OK - all example regex compile")

    # 3. Validate main.py _PUBLISH_DENY_PATTERNS by importing it.
    print("[3] Importing main module to verify _PUBLISH_DENY_PATTERNS...")
    try:
        import main  # noqa: F401
        print("    OK - main imports cleanly")
    except Exception as exc:
        failures.append(f"main.py import failed: {exc}")

    # 4. Test deny cases against ObjectiveScorer.
    scorer = ObjectiveScorer()
    print(f"[4] Running {len(DENY_TEST_CASES)} deny test cases...")
    for label, text, should_block in DENY_TEST_CASES:
        result = scorer._score_forbidden_phrases(text, forbidden)
        blocked = result["grade"] == "Fail"
        if blocked != should_block:
            failures.append(
                f"DENY MISMATCH [{label}]: blocked={blocked} "
                f"expected={should_block} text={text[:60]!r} hits={result['hits'][:2]}"
            )
        else:
            mark = "BLOCK" if blocked else "PASS "
            print(f"    [{mark}] {label}")

    # 5. Test sanitizer cases.
    print(f"[5] Running {len(SANITIZER_CASES)} sanitizer cases...")
    for label, text, expected in SANITIZER_CASES:
        cleaned, removed = sanitize(text)
        if expected is None:
            if removed:
                failures.append(
                    f"SANITIZER FALSE-POSITIVE [{label}]: "
                    f"removed={removed} text={text[:60]!r}"
                )
            else:
                print(f"    [PASS]  {label}")
        else:
            has_match = any(expected in r for r in removed)
            if not has_match:
                failures.append(
                    f"SANITIZER MISS [{label}]: expected={expected!r} "
                    f"got removed={removed} text={text[:60]!r}"
                )
            else:
                print(f"    [STRIP] {label}")

    # 6. Summary.
    print()
    if failures:
        print(f"FAIL: {len(failures)} test(s) failed:")
        for f in failures:
            print(f"  - {f}")
        return 1
    print(f"PASS: all {len(DENY_TEST_CASES)} deny + {len(SANITIZER_CASES)} sanitizer cases OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
